const fs=require('fs');
const path=require('path');
const appPath=path.join(__dirname,'..','app','src','main','assets','app.js');
const src=fs.readFileSync(appPath,'utf8');
new Function(src);
const names=[...src.matchAll(/^function\s+([A-Za-z_$][\w$]*)\s*\(/gm)].map(m=>m[1]);
const seen=new Map(); for(const n of names)seen.set(n,(seen.get(n)||0)+1);
const dup=[...seen].filter(([,c])=>c>1);
if(dup.length)throw new Error('Duplicate function declarations: '+JSON.stringify(dup));
if(/bindPageV\w*Base/.test(src))throw new Error('Legacy bindPage override chain still exists');
if(/openGoalModalV68Base/.test(src))throw new Error('Legacy openGoalModal self-alias still exists');
if(/^\/\*\s*=====\s*UANGKU\s+V[0-7]/mi.test(src))throw new Error('Historical patch header remains');
if(!src.includes('UangKu v8.5 Native Voice Fix + Receipt Scanner + Performance Hardening + Theme + Daily Use Hardening'))throw new Error('v8.4 runtime header missing');
if(src.includes("new Date().toISOString().slice(0,10)"))throw new Error('UTC date helper regression detected');
const bindStart=src.indexOf('function bindPage(){');
const bindEnd=src.indexOf('\n\nfunction accountName',bindStart);
const bindSrc=src.slice(bindStart,bindEnd);
const txSubmitCount=(bindSrc.match(/\$\('#txForm'\)\.onsubmit/g)||[]).length;
if(txSubmitCount!==1)throw new Error('bindPage must have exactly one final txForm submit binding, got '+txSubmitCount);
console.log(`code-health: OK (${names.length} unique named functions, ${src.length} chars)`);
