const fs=require('fs');
const vm=require('vm');
const path=require('path');
const appPath=path.join(__dirname,'..','app','src','main','assets','app.js');
let src=fs.readFileSync(appPath,'utf8').replace("setHeader('home');render();",'');
function assert(cond,msg){if(!cond)throw new Error(msg)}
function eq(actual,expected,msg){if(actual!==expected)throw new Error(`${msg}: expected ${expected}, got ${actual}`)}
const dummy={classList:{toggle(){},add(){},remove(){}},style:{},dataset:{},textContent:'',value:'',innerHTML:'',onclick:null,onchange:null,onsubmit:null,onkeydown:null,click(){},focus(){},setAttribute(){},addEventListener(){},querySelectorAll(){return[]},closest(){return null},scrollTo(){},clientWidth:320,scrollLeft:0,scrollHeight:0};
const storage={};
const context={console,window:{scrollTo(){},Native:null},document:{querySelector(){return dummy},querySelectorAll(){return[]},createElement(){return dummy},addEventListener(){}},localStorage:{getItem(k){return storage[k]??null},setItem(k,v){storage[k]=String(v)},removeItem(k){delete storage[k]}},requestAnimationFrame(fn){fn();return 1},setTimeout(){return 0},clearTimeout(){},confirm(){return false},FormData:global.FormData,Blob:global.Blob,URL:global.URL,Date,Math,JSON,Intl,Number,String,Array,Object,Set,Map,RegExp,Promise};
context.global=context; vm.createContext(context); vm.runInContext(src,context,{filename:'app.js'});
const demo={profile:{name:'Firda'},accounts:[{id:'sea',name:'SEABANK',type:'Bank',initial:1000000},{id:'cash',name:'Cash',type:'Cash',initial:500000},{id:'ew',name:'DANA',type:'e-Wallet',initial:250000},{id:'save',name:'Saving',type:'Tabungan',initial:3000000},{id:'titip',name:'Uang di Ibu',type:'Titipan',initial:2000000}],categories:['Makan & Minum','Transportasi','Groceries','Listrik','Pakan Hewan','Hadiah','Hiburan','Penyesuaian Saldo','Kantor','Lainnya','Penjualan','Utang & Cicilan'],categoryIcons:{},categoryGroups:{},transactions:[{id:'salary',type:'income',date:'2026-09-01',amount:2000000,accountId:'sea',category:'Kantor',note:'Gaji'},{id:'food',type:'expense',date:'2026-09-02',amount:100000,accountId:'sea',category:'Makan & Minum',note:'Makan'},{id:'sale',type:'income',date:'2026-09-03',amount:100000,cashAmount:30000,accountId:'cash',category:'Penjualan',note:'Jual Dimsum',source:'sale_receivable_origin',salePaymentStatus:'partial',saleCustomer:'Siti',debtId:'saleDebt'}],budgets:[{id:'b1',month:'2026-09',category:'Makan & Minum',limit:300000}],goals:[{id:'g1',name:'Dana Darurat',target:10000000,legacyCurrent:0,allocations:[{id:'ga1',accountId:'save',amount:1000000,date:'2026-08-01',source:'legacy_link'}],logo:'🎯'},{id:'g2',name:'HP Baru',target:5000000,legacyCurrent:0,allocations:[{id:'ga2',accountId:'sea',amount:200000,date:'2026-09-05',source:'new_goal_allocation'}],logo:'📱'}],assets:{investment:[],property:[],physical:[]},debts:[{id:'loan',type:'payable',person:'YUP',principal:500000,amount:500000,paid:100000,status:'active'},{id:'friend',type:'receivable',person:'Teman',principal:300000,amount:300000,paid:50000,status:'active'},{id:'saleDebt',type:'receivable',person:'Siti',principal:100000,amount:100000,paid:30000,status:'active',receivableKind:'sale',saleOriginTxId:'sale',saleDate:'2026-09-03',payments:[{id:'sp0',txId:'sale',date:'2026-09-03',amount:30000,accountId:'cash',source:'sale_initial_payment'}]}],bills:[{id:'bill',name:'Internet',amount:150000,status:'active',dueDate:'2026-09-20'}],chat:[]};
context.demo=demo;
vm.runInContext("globalThis.__getState=()=>state; globalThis.__setState=s=>{state=s}; globalThis.__setOpenModal=f=>{openModal=f};",context);
vm.runInContext("state=normalizeState(demo); homePeriod='2026-09'; planPeriod='2026-09'; reportPeriod='2026-09'; netWorthExpanded=false; includeInvestmentAssets=false;",context);
for(const name of ['renderHome','renderTransactions','renderAddTransaction','renderAssistant','renderAccounts','renderPlans','renderAssets','renderDebtsBills','renderMore','renderReports','renderCategories','renderSettings']){const out=context[name]();assert(typeof out==='string'&&out.length>0,`${name} did not render`)}
context.bindPage();
const home=context.renderHome(); assert(home.includes('inout-vertical-v711'),'vertical income/expense layout missing'); assert(!home.includes('Arus Kas Sep'),'removed cash-flow card returned'); assert((home.match(/data-finance-slide=/g)||[]).length===3,'financial carousel must have 3 slides');
const moving=context.movingAccountsV78(); eq(moving.length,3,'moving account count'); assert(!moving.some(a=>['Tabungan','Titipan'].includes(a.type)),'non-moving account included');
const beforeTransferBalance=context.totalBalance(), beforeTransferNet=context.netWorthValue(); context.__getState().transactions.push({id:'tr1',type:'transfer',date:'2026-09-06',amount:50000,fromAccountId:'sea',toAccountId:'cash',category:'Transfer'}); eq(context.totalBalance(),beforeTransferBalance,'transfer total balance invariant'); eq(context.netWorthValue(),beforeTransferNet,'transfer net worth invariant');
const debt=context.__getState().debts.find(d=>d.id==='loan'), nwBeforeDebtPay=context.netWorthValue(); debt.paid+=100000; context.__getState().transactions.push({id:'dp',type:'expense',date:'2026-09-07',amount:100000,accountId:'sea',category:'Utang & Cicilan',debtId:'loan'}); eq(context.netWorthValue(),nwBeforeDebtPay,'debt payment net worth invariant');
const rec=context.__getState().debts.find(d=>d.id==='friend'), nwBeforeRec=context.netWorthValue(); rec.paid+=100000; context.__getState().transactions.push({id:'rp',type:'income',date:'2026-09-08',amount:100000,accountId:'cash',category:'Piutang',debtId:'friend'}); eq(context.netWorthValue(),nwBeforeRec,'receivable payment net worth invariant');
const sales=context.salesSummary('2026-09'); eq(sales.omzet,100000,'sales omzet'); eq(sales.receivable,70000,'sales receivable'); assert(sales.received>=30000,'sales received should include cash actually received');
const sav=context.monthlySavingsAddedV65('2026-09'); assert(sav.legacyGoalLinked>=0,'legacy savings field missing'); assert(sav.goalFromNonSavings>=200000,'new goal allocation not counted');
const rows=context.budgetTransactionsV75(context.__getState().budgets[0]); assert(rows.some(t=>t.id==='food'),'budget transaction missing'); assert(rows.every(t=>t.category==='Makan & Minum'&&t.date.startsWith('2026-09')),'budget detail scope incorrect');
eq(context.parseAmountV79('keluar dua puluh lima ribu makan'),25000,'spoken 25k parser'); eq(context.parseAmountV79('masuk satu juta dua ratus ribu'),1200000,'spoken 1.2m parser'); let reply=context.assistantProcess('saldo seabank berapa'); assert(reply.includes('SEABANK'),'assistant account answer'); reply=context.assistantProcess('sisa utang berapa'); assert(reply.includes('Sisa utang'),'assistant debt answer'); reply=context.assistantProcess('budget makan bulan ini'); assert(reply.includes('Budget Makan & Minum'),'assistant budget answer');
context.__setOpenModal(()=>{}); let goalOk=true; try{context.openGoalModal('')}catch(e){goalOk=false;console.error(e)} assert(goalOk,'openGoalModal recursion/regression');
console.log('finance-smoke: OK');
